# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: r
cache: packages

sudo: false

warnings_are_errors: false

jobs:
  include:
    - stage: soilwaterfun
      env:
        - PACK_DIR=soilwaterfun
      r:
        - release
        - 3.1
    - stage: soilwaterptf
      env:
        - PACK_DIR=soilwaterptf
      r_github_packages: julienmoeys/soilwater/pkg/soilwaterfun
      r:
        - release
        - 3.1

before_install:
  - cd pkg/$PACK_DIR

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
 